from __future__ import annotations

from html import escape
from typing import Any

from suffice.models import AgentRunResult


def render_html_report(title: str, metrics: dict[str, Any], cases: list[AgentRunResult]) -> str:
    cards = "".join(
        _card(label, metrics.get(key))
        for label, key in (
            ("Success rate", "success_rate"),
            ("Average tokens / task", "average_tokens_per_task"),
            ("Median tokens / task", "median_tokens_per_task"),
            ("Tokens / successful task", "tokens_per_successful_task"),
            ("Input tokens", "input_tokens"),
            ("Output tokens", "output_tokens"),
            ("Tool overhead", "tool_overhead"),
            ("Context overhead", "context_overhead"),
        )
    )
    rows = "".join(
        f"<tr><td>{escape(str(case.metadata.get('task_id', '')))}</td>"
        f"<td class={'pass' if case.success else 'fail'}>{'PASS' if case.success else 'FAIL'}</td>"
        f"<td>{case.token_trace.total if case.token_trace.total is not None else 'N/A'}</td>"
        f"<td><code>{escape(str(case.output))}</code></td></tr>"
        for case in cases
    )
    styles = (
        "body{font:16px system-ui;margin:0;background:#0b1020;color:#eef2ff}"
        "main{max-width:1100px;margin:auto;padding:3rem 1.5rem}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:1rem}"
        ".card{background:#172036;padding:1rem;border-radius:10px}"
        ".value{font-size:1.7rem;font-weight:700;color:#7dd3fc}"
        "table{width:100%;border-collapse:collapse;margin-top:2rem;background:#172036}"
        "th,td{padding:.8rem;text-align:left;border-bottom:1px solid #334155}"
        ".pass{color:#86efac}.fail{color:#fca5a5}code{white-space:pre-wrap}"
    )
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width">'
        f"<title>{escape(title)} — Suffice</title><style>{styles}</style></head>"
        f"<body><main><h1>{escape(title)}</h1>"
        "<p>Generated by Suffice. Token provenance is stored in cases.jsonl.</p>"
        f'<section class="grid">{cards}</section><table><thead><tr>'
        "<th>Task</th><th>Result</th><th>Total tokens</th><th>Output</th>"
        f"</tr></thead><tbody>{rows}</tbody></table></main></body></html>"
    )


def _card(label: str, value: Any) -> str:
    shown = "N/A" if value is None else f"{value:.2f}" if isinstance(value, float) else str(value)
    return f'<div class="card"><div>{escape(label)}</div><div class="value">{shown}</div></div>'
